baseURL = "https://www.zachwhitehead.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Zach Whitehead Â· Web & Mobile Developer, all-around coder"
theme = "adritian"


# Languages
#   en
#     weight: 1
#   es
#     weight: 2

[build]
  writeStats = true

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "css/main.css"
  [[params.plugins.css]]
  link = "css/rad-icons.css"
  [[params.plugins.css]]
  link = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"


# navigation
[menu]

  # [[menu.header]]
  # name = "About"
  # URL = "index.html#about"
  # weight = 2

  # [[menu.header]]
  # name = "Experience"
  # URL = "index.html#experience"
  # weight = 3

  # [[menu.header]]
  # name = "Contact"
  # URL = "#contact"
  # weight = 4


  # [[menu.footer]]
  # name = "ğŸ’â€â™‚ï¸ About"
  # URL = "index.html#about"
  # weight = 2


  # [[menu.footer]]
  # name = "ğŸ“š Books"
  # URL = "/books"
  # weight = 3

  # [[menu.footer]]
  # name = "ğŸ¤ Public Speaking"
  # URL = "/public-speaking"
  # weight = 4

  # [[menu.footer]]
  # name = "ğŸ“¨ Contact"
  # URL = "index.html#contact"
  # weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "contact"]
  googleTagManagerID = "" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Zach"
    text2 = "Whitehead"

  [params.footer]
      copyright = "Â© Zach Whitehead . <a href=\"https://github.com/zjwhitehead/zachwhitehead.com\">Code available on GitHub</a>."

[taxonomies]
  book_author = "book_authors"
  book_category = "book_categories"
